apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-trek-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttproject
  template:
    metadata:
      labels:
        app: ttproject
    spec:
      containers:
      - name: ttproject
        image: culceanluca/ttproject:1
        ports:
        - containerPort: 8080
